language: python
python:
  - "2.7"
  - "3.3"

before_install:
# apt-get packages first.
- echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get install -y gradle lintian devscripts shellcheck
- sudo apt-get install -y oracle-java8-set-default
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 lib32z1 libreadline6-dev:i386 libncurses5-dev:i386; fi

- if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
- unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

# Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;26.0.1' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-22' > /dev/null
- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'system-images;android-22;default;x86' > /dev/null
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle

# Create and start a AVD
- echo no | $HOME/android-sdk/tools/bin/avdmanager create avd --force -n test -k "system-images;android-22;default;x86"
- emulator -avd test -no-skin -no-audio -no-window &

install:
- pip install -r "requirements.txt"
- pip install setuptools==28.7.1

before_script:
# Wait for emulator
- ./wait_for_emulator

script: ./gradlew useDebugApk doCoverage

branches:
  only:
  - dev

git:
  depth: 5

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

env:
- ANDROID_HOME=$HOME/android-sdk

