language: python
python:
  - "2.7"
  - "3.3"

before_install:
# apt-get packages first.
- echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
- sudo apt-get -qq update
- sudo apt-get install -y gradle lintian devscripts shellcheck
- sudo apt-get install -y oracle-java8-set-default
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 lib32z1 libreadline6-dev:i386 libncurses5-dev:i386; fi

# We need to manually grab the SDK
- wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
- tar xzf android-sdk_r24.4.1-linux.tgz
- export ANDROID_HOME=${PWD}/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle

# We also need to grab the build tools.
- echo y | android update sdk --all --filter platform-tools,build-tools-25.0.1,android-22,android-25,extra-android-m2repository,sys-img-x86-android-22 --no-ui --force

# Create and start a AVD
- echo no | android create avd --force -n test -t android-22 --abi x86
- emulator -avd test -no-skin -no-audio -no-window &

install:
- pip install -r "requirements.txt"
- pip install setuptools==28.7.1

before_script:
# Wait for emulator
- ./wait_for_emulator

script: ./gradlew useDebugApk doCoverage

branches:
  only:
  - dev

git:
  depth: 5
